<?php
if ( ! defined( 'ABSPATH' ) ) exit;

// Tables:
// - customers: one row per customer (phone-first identity) with maintained statistics and the current reminder cycle.
// - orders:    a small index of WooCommerce orders (id, customer, status, net total, date), kept in sync through order
//              hooks, so statistics come from indexed SQL instead of loading order history. Filled via WC_Order APIs.
// - contacts:  every WhatsApp contact (one per click): message, voucher, offer-link opens, and how the cycle ended.
// - coupons:   vouchers generated by this plugin and what happened to them.
class WCR_DB {
    public static function customers_table() { global $wpdb; return $wpdb->prefix . 'wcr_customers'; }
    public static function orders_table() { global $wpdb; return $wpdb->prefix . 'wcr_orders'; }
    public static function contacts_table() { global $wpdb; return $wpdb->prefix . 'wcr_contacts'; }
    public static function coupons_table() { global $wpdb; return $wpdb->prefix . 'wcr_coupons'; }

    public static function install() {
        global $wpdb;
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        $charset   = $wpdb->get_charset_collate();
        $customers = self::customers_table();
        $orders    = self::orders_table();
        $contacts  = self::contacts_table();
        $coupons   = self::coupons_table();
        $sql = "CREATE TABLE $customers (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            customer_key VARCHAR(191) NOT NULL,
            user_id BIGINT UNSIGNED NULL,
            name VARCHAR(255) NULL,
            phone VARCHAR(100) NULL,
            wa_number VARCHAR(20) NOT NULL DEFAULT '',
            email VARCHAR(320) NULL,
            details_at DATETIME NULL,
            order_count INT UNSIGNED NOT NULL DEFAULT 0,
            total_value DECIMAL(20,6) NOT NULL DEFAULT 0,
            first_order_at DATETIME NULL,
            last_order_id BIGINT UNSIGNED NULL,
            last_order_at DATETIME NULL,
            open_order_id BIGINT UNSIGNED NULL,
            open_order_status VARCHAR(30) NULL,
            open_order_at DATETIME NULL,
            last_contact_at DATETIME NULL,
            last_contact_by BIGINT UNSIGNED NULL,
            last_contact_type VARCHAR(10) NULL,
            last_contact_channel VARCHAR(10) NULL,
            cycle_contacts INT UNSIGNED NOT NULL DEFAULT 0,
            cycle_voucher TINYINT(1) NOT NULL DEFAULT 0,
            conversions INT UNSIGNED NOT NULL DEFAULT 0,
            last_converted_order_id BIGINT UNSIGNED NULL,
            last_converted_at DATETIME NULL,
            dnc TINYINT(1) NOT NULL DEFAULT 0,
            dnc_at DATETIME NULL,
            dnc_email TINYINT(1) NOT NULL DEFAULT 0,
            dnc_email_at DATETIME NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY  (id),
            UNIQUE KEY customer_key (customer_key),
            KEY last_order_at (last_order_at),
            KEY order_count (order_count),
            KEY total_value (total_value),
            KEY last_contact_at (last_contact_at),
            KEY user_id (user_id),
            KEY email (email(191)),
            KEY wa_number (wa_number)
        ) $charset;
        CREATE TABLE $orders (
            order_id BIGINT UNSIGNED NOT NULL,
            customer_id BIGINT UNSIGNED NOT NULL,
            status VARCHAR(30) NOT NULL,
            net_total DECIMAL(20,6) NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL,
            synced_at DATETIME NOT NULL,
            PRIMARY KEY  (order_id),
            KEY customer_status (customer_id, status, created_at),
            KEY status (status),
            KEY synced_at (synced_at)
        ) $charset;
        CREATE TABLE $contacts (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            customer_id BIGINT UNSIGNED NOT NULL,
            anchor_order_id BIGINT UNSIGNED NULL,
            created_at DATETIME NOT NULL,
            created_by BIGINT UNSIGNED NULL,
            type VARCHAR(10) NOT NULL,
            channel VARCHAR(10) NOT NULL DEFAULT 'whatsapp',
            coupon_id BIGINT UNSIGNED NULL,
            wa_number VARCHAR(20) NOT NULL DEFAULT '',
            email_to VARCHAR(320) NULL,
            subject VARCHAR(255) NULL,
            error VARCHAR(255) NULL,
            message TEXT NULL,
            token_hash CHAR(64) NULL,
            link_opens INT UNSIGNED NOT NULL DEFAULT 0,
            first_open_at DATETIME NULL,
            last_open_at DATETIME NULL,
            last_device VARCHAR(100) NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'contacted',
            closed_at DATETIME NULL,
            order_id BIGINT UNSIGNED NULL,
            order_value DECIMAL(20,6) NULL,
            converted_at DATETIME NULL,
            coupon_used TINYINT(1) NOT NULL DEFAULT 0,
            PRIMARY KEY  (id),
            UNIQUE KEY token_hash (token_hash),
            KEY customer_status (customer_id, status),
            KEY status (status),
            KEY created_at (created_at),
            KEY coupon_id (coupon_id)
        ) $charset;
        CREATE TABLE $coupons (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            customer_id BIGINT UNSIGNED NOT NULL,
            active_customer_id BIGINT UNSIGNED NULL,
            wc_coupon_id BIGINT UNSIGNED NULL,
            code VARCHAR(40) NOT NULL,
            discount_type VARCHAR(10) NOT NULL,
            amount DECIMAL(20,6) NOT NULL,
            min_spend DECIMAL(20,6) NULL,
            max_discount DECIMAL(20,6) NULL,
            usage_limit INT UNSIGNED NOT NULL DEFAULT 1,
            individual_use TINYINT(1) NOT NULL DEFAULT 1,
            restrict_email TINYINT(1) NOT NULL DEFAULT 0,
            valid_days INT UNSIGNED NOT NULL DEFAULT 0,
            cycle_start DATETIME NULL,
            expires_at DATETIME NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'generated',
            created_at DATETIME NOT NULL,
            created_by BIGINT UNSIGNED NULL,
            sent_at DATETIME NULL,
            used_at DATETIME NULL,
            order_id BIGINT UNSIGNED NULL,
            discount_total DECIMAL(20,6) NULL,
            revoked_at DATETIME NULL,
            revoked_by BIGINT UNSIGNED NULL,
            revoke_reason VARCHAR(100) NULL,
            PRIMARY KEY  (id),
            UNIQUE KEY code (code),
            UNIQUE KEY active_customer_id (active_customer_id),
            KEY customer_status (customer_id, status),
            KEY status (status),
            KEY order_id (order_id)
        ) $charset;";
        $from = (string) get_option( 'wcr_db_version', '0' );
        dbDelta( $sql );
        // 1.0.0 → 1.1.0: vouchers get no end date until sent (dbDelta does not relax NOT NULL), and 'active' became
        // generated / sent.
        if ( '0' !== $from && version_compare( $from, '1.1.0', '<' ) ) {
            $wpdb->query( "ALTER TABLE $coupons MODIFY expires_at DATETIME NULL" );
            $wpdb->query( "UPDATE $coupons cp SET cp.sent_at = (SELECT MIN(k.created_at) FROM $contacts k WHERE k.coupon_id = cp.id AND k.status <> 'undone') WHERE cp.sent_at IS NULL" );
            $wpdb->query( "UPDATE $coupons SET status = IF(sent_at IS NULL, 'generated', 'sent') WHERE status = 'active'" );
            $settings = get_option( WCR_Settings::OPTION );
            if ( is_array( $settings ) && isset( $settings['template_voucher'] ) && str_replace( "\r\n", "\n", $settings['template_voucher'] ) === WCR_Settings::LEGACY_VOUCHER ) {
                $settings['template_voucher'] = WCR_Settings::DEFAULT_VOUCHER;
                update_option( WCR_Settings::OPTION, $settings );
            }
        }
        if ( false === get_option( WCR_Settings::OPTION ) ) add_option( WCR_Settings::OPTION, WCR_Settings::defaults() );
        // The customer list is built from existing orders in the background (Action Scheduler), started on 'init'.
        if ( false === get_option( 'wcr_rebuild' ) ) update_option( 'wcr_needs_rebuild', 1, false );
        update_option( 'wcr_db_version', WCR_VERSION );
    }
    public static function maybe_upgrade() {
        if ( get_option( 'wcr_db_version' ) !== WCR_VERSION ) self::install();
    }
    public static function schedule() {
        if ( ! wp_next_scheduled( 'wcr_daily' ) ) wp_schedule_event( time() + HOUR_IN_SECONDS, 'daily', 'wcr_daily' );
    }
    public static function daily() {
        WCR_Coupons::expire_due();
        WCR_Privacy::purge_old();
    }
    public static function deactivate() {
        wp_clear_scheduled_hook( 'wcr_daily' );
        if ( function_exists( 'as_unschedule_all_actions' ) ) as_unschedule_all_actions( WCR_Customers::REBUILD_HOOK, array(), 'wcr' );
        // A rebuild cut short by deactivation starts again on reactivation.
        $state = get_option( 'wcr_rebuild' );
        if ( is_array( $state ) && 'running' === $state['status'] ) update_option( 'wcr_needs_rebuild', 1, false );
    }
}
